### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Tee86** [speecil/PauseRemapper#1]
Hi,
Please, can you explain how this mod work? Have it activated via BMBF but can't see any option in-game for remapping... Running v1.25.1 on Q2

**Comment by NuggoDEV** [comment]
Go to the song selection screen and look left where your modifiers are at, after that look up a bit and press on the "Mods" button and open the PauseRemapper settings.

Hope that helps :)

**Comment by Tee86** [comment]
Yes, it did. Thank you very much for your hard work. Hopefully, Chroma and NE will come soon for 1.27 from you, amazing developers! All the best
